<html>
<head>
<style>
img {
	margin-right:10px;
}
body {
	margin-left:20%;
	margin-right:20%;
}
</style>

<link rel="stylesheet" type="text/css" href="layout/styles/style.css" />
</head>

<body>
<br>
<?php #require('login.php');?>

<!--
<hr>
<br>
-->

<h6>DROPLET DIGITAL PCR</h6>
<br>
<table>
  <tr><center><img src="layout/ddpcr.png" style="width:500"></center></tr>
  <tr>
	<td>
	<br>
	<h6>A. INTRODUCTION<h6>
	<br>
	<p>Droplet Digital polymerase chain reaction (ddPCR) was developed to provide high-precision, absolute quantification of nucleic acid target sequences wait wide-ranging applications for both research and clinical diagnostic applications. ddPCR measures absolute quantities by counting nucleic acid molecules encapsulated in discrete, volumetrically defined water-in-oil droplet partitions. Droplet Digital PCR using Bio-Rad’s QX100 or QX200 Droplet Digital PCR system overcomes the previous lack of scalable and practical technologies for digital PCR implementation. </p>
	<br><br>
	<h6>B. APPLICATIONS<h6>
	<br>
	<p><b>Absolute quantification:</b> ddPCR provides a concentration of target DNA copies per input sample without the need for running standard curves, making this technique ideal for target DNA measurements, viral load analysis, and microbial quantification.
	<br><br>
	<b>Genomic alterations such as gene copy number variation (CNV):</b> CNVs result in too few or too many dosage-sensitive genes responsible for phenotypic variability, complex behavioral traits, and disease. ddPCR enables measurement of 1.2x differences in gene copy number.
	<br><br>
	<b>Detection of rare sequences:</b> Researchers must amplify single genes in a complex sample, such as a few tumor cells in a wild-type background. ddPCR is sensitive enough to detect rare mutations or sequences.
	<br><br>
	<b>Gene expression and microRNA analysis:</b> ddPCR provides stand-alone absolute quantification of expression levels, especially low-abundance microRNAs, with sensitively and precision.
	<br><br>
	<b>Next-generation sequencing (NGS):</b> ddPCR quantifies NGS sample library preparations to increase sequencing accuracy and reduce run repeats. Validate sequencing results such as single nucleotide polymorphisms or copy number variations with absolute quantification.
	<br><br>
	<b>Single cell analysis:</b> The high degree (10- to 100- fold) of cell-cell variation in gene expression and genomic content among homogeneous post-mitotic, progenitor, and stem cell populations drives a need for analysis from single cells. ddPCR enables low copy number quantification.
	<br><br>
	<b>Genome edit detection:</b> ddPCR enables fast, precise, and cost-effective assessment of HDR (Homology directed repair) and NHEJ (Non-homologous end joining) generated by CRISPR-Cas9 or other genome editing tools.</p>
	<br><br>
	<h6>C. DESIGNING PRIMERS<h6>
	<br>
	<p>Widely accepted quantitative PCR (qPCR) design guidelines apply to ddPCR primer design. Important criteria for single primers include melting temperature (Tm), length, base composition, and GC content. In addition, because primers are used in pairs, ensure that paired primers do not exhibit significant complementarity between 3’ ends because this can result in primer-dimers. Extensive primer-dimer formations can significantly decrease or prevent amplification. The QX200 Droplet Digital PCR System will support both hydrolysis probe (TaqMan) and DNA binding dye (EvaGreen) assay. All information in this chapter applies to both types of assay, except for the Designing Probes section (See more in protocol).</p>
	<br><br>
	<h6>D. DESIGNING PROBES<h6>
	<br>
	<p>The QX200 System is compatible with TaqMan hydrolysis probes and EvaGreen double-stranded DNA (dsDNA) binding dye. Advantages of using hydrolysis probes include high specificity, a high signal-to-noise ratio, and the ability to perform multiplex reactions. Hydrolysis assays include a sequence-specific, fluorescently labeled oligonucleotide probe in addition to the sequence-specific primers. TaqMan assays exploit the 5’ exonuclease activity of certain thermostable polymerases. The hydrolysis probe is labeled with a fluorescent reporter at the 5’ end and a quencher at the 3’ end (See more in protocol).</p>
	<br><br>
	<h6>E. PREPARING THE SUPERMIX AND OIL<h6>
	<br>
	<p>There are unique Supermix and Droplet Generation Oil for Probe based ddPCR and EvaGreen based ddPCR. Carefully to choose the right reagent and oil that are for your experiment plan. </p>
	<br><br>	
	<h6>F. REQUEST CONSUMABLES FROM THE CORE<h6>
	<br>
	<p>Our core provides the consumables including cartridges, gaskets, ddPCR 96-Well Plates, and foil seal for users to request. Once you have prepared the required stuff, read through the protocol and you can start.</p>
	<br><br>
	<p>For more information, refer to the following links:</p>
	<br><br>
	<p>1. Droplet Digital&trade; PCR Applications Guide - Bio-Rad: <a class="button" target="_blank" href="http://www.bio-rad.com/webroot/web/pdf/lsr/literature/Bulletin_6407.pdf">Click</a></p>
	<br>
	<p>2. ddPCR&trade; Supermix for Probes - Bio-Rad: <a class="button" target="_blank" href="http://www.bio-rad.com/webroot/web/pdf/lsr/literature/10026235.pdf">Click</a></p>
	<br>
	<p>3. QX200&trade; ddPCR&trade; EvaGreen&reg; Supermix - Bio-Rad: <a class="button" target="_blank" href="http://www.bio-rad.com/webroot/web/pdf/lsr/literature/10028376.pdf">Click</a></p>
	<br><br>
	<p>If you have any queries, please contact our laboratory personnel here&nbsp;&nbsp;<a href="contactus.php#lab_personnel" class="button">Click</a>
	</p>
	<br><br>
	</td>
  </tr>
</table>

</body>
</html>

	
	
	